# name: pre-commit

# on:
#   pull_request:
#   push:
#     branches: 
#       - master
#       - dev

# jobs:
#   pre-commit:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-python@v4
#     - name: clang format support
#       run: |
#         sudo apt update
#         sudo apt install clang-format cppcheck
#     - uses: pre-commit/action@v3.0.0
